[tool.poetry]
name = "noteapp"
version = "0.1.0"
description = ""
authors = ["Grzegorz Boroń"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
asgiref = "^3.6.0"
attrs = "^23.1.0"
build = "^0.10.0"
CacheControl = "^0.12.14"
certifi = "^2023.5.7"
charset-normalizer = "^3.1.0"
cleo = "^2.0.1"
colorama = "^0.4.6"
crashtest = "^0.4.1"
crispy-bootstrap5 = "^0.7"
distlib = "^0.3.6"
dj-database-url = "^2.0.0"
Django = "^4.0"
django-crispy-forms = "^2.0"
django-environ = "^0.10.0"
django-multiupload = "^0.6.1"
dulwich = "^0.21.5"
environ = "^1.0"
filelock = "^3.12.2"
gunicorn = "^20.1.0"
html5lib = "^1.1"
idna = "^3.4"
importlib-metadata = "^6.6.0"
installer = "^0.7.0"
jsonschema = "^4.17.3"
keyring = "^23.13.1"
lockfile = "^0.12.2"
more-itertools = "^9.1.0"
msgpack = "^1.0.5"
packaging = "^23.1"
pexpect = "^4.8.0"
Pillow = "^9.4.0"
pkginfo = "^1.9.6"
platformdirs = "^3.6.0"
poetry = "^1.5.1"
poetry-core = "^1.6.1"
poetry-plugin-export = "^1.4.0"
psycopg2 = "^2.9.6"
psycopg2-binary = "^2.9.5"
ptyprocess = "^0.7.0"
pyproject_hooks = "^1.0.0"
pyrsistent = "^0.19.3"
python-decouple = "^3.8"
pywin32-ctypes = "^0.2.0"
rapidfuzz = "^2.15.1"
requests = "^2.31.0"
requests-toolbelt = "^1.0.0"
shellingham = "^1.5.0.post1"
six = "^1.16.0"
sqlparse = "^0.4.3"
tomli = "^2.0.1"
tomlkit = "^0.11.8"
trove-classifiers = "^2023.5.24"
typing_extensions = "^4.6.3"
tzdata = "^2022.7"
urllib3 = "^1.26.16"
virtualenv = "^20.23.1"
webencodings = "^0.5.1"
whitenoise = {extras = ["brotli"], version = "^6.5.0"}
zipp = "^3.15.0"



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
