# Generated by Django 4.0 on 2023-03-15 17:05

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('note_text', models.TextField()),
                ('add_date', models.DateTimeField(verbose_name='added date')),
                ('edit_dates', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(blank=True, null=True, verbose_name='edit dates'), default=list, size=None)),
                ('images', models.ManyToManyField(blank=True, to='notes.Image')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note', to='auth.user')),
            ],
        ),
    ]
