# Generated by Django 4.1.7 on 2023-03-02 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='edit_dates',
        ),
    ]
