# Generated by Django 4.0 on 2023-03-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_remove_note_images_note_img_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='doc',
            field=models.FileField(blank=True, upload_to='files'),
        ),
    ]
