# Generated by Django 4.1.7 on 2023-03-02 16:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_remove_note_edit_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='edit_dates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(blank=True, null=True, verbose_name='edit dates'), default=list, size=None),
        ),
    ]
