# Generated by Django 4.0 on 2023-03-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_doc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.RemoveField(
            model_name='note',
            name='img',
        ),
        migrations.AlterField(
            model_name='note',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='added date'),
        ),
        migrations.AddField(
            model_name='note',
            name='images',
            field=models.ManyToManyField(blank=True, to='notes.Image'),
        ),
    ]
