# Generated by Django 4.0 on 2023-03-18 08:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_remove_note_images_note_img_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='doc',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(blank=True, upload_to='files'), default=list, size=None),
        ),
    ]
