# Generated by Django 4.0 on 2023-03-19 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_rename_doc_note_files_remove_note_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='files',
        ),
        migrations.CreateModel(
            name='NoteFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='files')),
                ('note', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.note')),
            ],
        ),
    ]
