# Generated by Django 4.0 on 2023-06-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_category_options_alter_note_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='allow_edits',
            field=models.BooleanField(default=True),
        ),
    ]
