# Generated by Django 4.0 on 2023-07-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_reminder_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='remind_date',
            field=models.DateTimeField(),
        ),
    ]
