# Generated by Django 4.0 on 2023-10-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_category_name_pl'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message_pl',
            field=models.TextField(default=''),
        ),
    ]
