# Generated by Django 4.0 on 2023-11-21 13:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_notification_message_pl'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='edit_authors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, size=None),
        ),
    ]
