# Generated by Django 4.0 on 2023-12-18 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_note_edit_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='category',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='notes.category'),
        ),
    ]
